apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-backend
  labels:
    app: inventory-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-backend
  template:
    metadata:
      labels:
        app: inventory-backend
    spec:
      containers:
        - name: backend
          image: inventory-backend:latest    # or your built image
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secret
