apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXMucmFpbHdheS5pbnRlcm5hbA==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bHVQbWdQWXpHaFF0RWZQdUpOaktncERTZkxrRXJ5dFQ=
  POSTGRES_DB: cmFpbHdheQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmx1UG1nUFl6R2hRdEVmUHVKTmpLZ3BEU2ZMa0VyeXRUQHBvc3RncmVzLnJhaWx3YXkuaW50ZXJuYWw6NTQzMi9yYWlsd2F5
  JWT_SECRET: eW91cl9zZWNyZXRfa2V5
