// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";  // Importing the Google Inter font
import Navbar from "./components/NavBar";  // Navbar component for the layout
import "./globals.css";  // Global CSS file for styling

// Loading the Inter font with the Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the page, such as title and description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component that wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  // Expecting children, i.e., the pages and content that will be rendered inside the layout
}>) {
  return (
    <html lang="en"> {/* Set the language for the HTML tag */}
      <body className={inter.className}> {/* Applying the Inter font */}
        <Navbar /> {/* Including the navigation bar on all pages */}
        <main>{children}</main> {/* Rendering the children (the page content) within the main tag */}
      </body>
    </html>
  );
}
