// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/NavBar";
import ClientThemeProvider from './ClientThemeProvider';  // Import the client-side theme provider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
