{
  "build": {
    "env": {
      "NODE_ENV": "production",
      "DB_PUBLIC_URL": "DB_PUBLIC_URL",
      "DB_HOST": "autorack.proxy.rlwy.net",
      "DB_PORT": "23628",
      "DB_USERNAME": "postgres",
      "DB_PASSWORD": "uqYOiTjNGfafaezPxcCROIWsvWSVzfqP",
      "DB_DATABASE": "postgres",
      "JWT_SECRET": "your_secret_key"
    }
  },
  "start": "npm start"
}
